rootProject.name = "nurupoga"
include("nurupoga-common-dependency")
include("nurupoga-common-configuration")
include("nurupoga-user-service")
include("nurupoga-post-service")
include("nurupoga-post-service")
include("nurupoga-auth-service")
include("nurupoga-gateway-service")
include("nurupoga-comment-service")
include("nurupoga-gitee-service")
include("nurupoga-tag-service")
include("nurupoga-notice-service")
include("nurupoga-follow-service")
include("nurupoga-common-configuration")
include("nurupoga-result")
