dependencies {
    api("${project.extra["nacos"]}")
    api("${project.extra["web"]}")
    api("${project.extra["mp"]}")
    api("${project.extra["sa"]}")
    api("${project.extra["sa-redis"]}")
    api("${project.extra["pool"]}")
    api("${project.extra["doc"]}")
    api("${project.extra["therapi"]}")
    api("${project.extra["aop"]}")
    api("${project.extra["openfeign"]}")
    api("${project.extra["loadbalancer"]}")
    api("${project.extra["devtools"]}")
    api(project(":nurupoga-result"))
}